### ISSUE TITLE
[meta] Working Draft publication requirements

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#123]
As signaled by the [CfC][1], the group is planning to publish a new Working Draft of the Presentation API.

This meta issue ensures we meet the W3C Process requirements for "Revising Public Working Drafts" and also provides transparency into the W3C Process this group follows.

Per the [W3C Process][2], to publish a revision of a Working Draft, a Working Group:

* [x] MUST record the group's decision to request publication. Consensus is not required, as this is a procedural step,
 * [CfC to publish a revised WD][1] to end 29 July 2015.
* [x] MUST provide public documentation of substantive changes to the technical report since the previous Working Draft,
 * A link to the [version history][3] is provided at the top of the document.
* [x] SHOULD provide public documentation of significant editorial changes to the technical report since the previous step,
 * As above.
* [x] SHOULD report which, if any, of the Working Group's requirements for this document have changed since the previous step,
 * No changes.
* [x] SHOULD report any changes in dependencies with other groups,
 * No changes (to [dependencies][4] as documented in the Charter).

@tidoust My expectation is that:
* the [version history][3] link is considered "public documentation" (alternatives being e.g. a bullet list of key changes in SoTD, or a standalone "Changes since" section that are snapshots in time) and that,
* to satisfy the two last SHOULDs no text is required in the SoTD.

[1]: https://lists.w3.org/Archives/Public/public-secondscreen/2015Jun/0181.html
[2]: http://www.w3.org/2014/Process-20140801/#revised-wd
[3]: https://github.com/w3c/presentation-api/commits/
[4]: http://www.w3.org/2014/secondscreen/charter.html#dependencies

**Comment by tidoust** [comment]
@anssiko re. your expectations, I confirm.

**Comment by anssiko** [comment]
@tidoust Thanks for the confirmation.

@mfoltzgoogle We tick all the boxes and are ready to publish the Working Draft after the CfC closes. That means the earliest publication opportunity is 30 June 2015. I suggest we attempt to publish on that day.

**Comment by mfoltzgoogle** [comment]
Sounds good.  Assuming consensus, I will use the process documented here [1] to publish a Working Draft on 6/30.

https://www.w3.org/wiki/Second_Screen/Work_Mode#Publication_as_Working_Draft

**Comment by tidoust** [comment]
Working draft was published on 1 July 2015:
http://www.w3.org/TR/2015/WD-presentation-api-20150701/

Closing this meta issue as a consequence.

Automation worked as intended on our side, but did not work out so well with Echidna. 3 issues were raised on Echidna:
* the publishing tool fails to process links with trailing spaces (https://github.com/w3c/echidna/issues/201)
* Echidna fails to report tasks that fail at the publishing step (https://github.com/w3c/echidna/issues/202)
* The CSS validator refuses to check HTML documents served with MIME type text/plain, meaning that raw content addresses (served from `https://raw.githubusercontent.com`) and thus branches other than `gh-pages` cannot easily be used. Solution was to go through RawGit but the use of caching might be an issue in the future (https://github.com/w3c/echidna/issues/203)
