### ISSUE TITLE
[meta] First Public Working Draft publication requirements

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#56]
This is the meta issue to ensure we meet the W3C Process requirements for the First Public Working Draft publication.

Per the W3C Process [1], to publish the First Public Working Draft of a document, a Working Group must meet the applicable general requirements for advancement, enumerated below:

* [x] must record the group's decision to request advancement.
  * CfC ended without concerns
* [x] must obtain Director approval. 
* [x] must provide public documentation of all substantive changes to the technical report since the previous publication.
  * not applicable, since this is a FPWD
* [x] must formally address all issues raised about the document since the previous maturity level.
  * not applicable, since this is a FPWD
* [x] must provide public documentation of any Formal Objections.
  * no FOs
* [x] should provide public documentation of changes that are not substantive.
* [x] should report which, if any, of the Working Group's requirements for this document have changed since the previous step.
* [x] should report any changes in dependencies with other groups.
* [x] should provide information about implementations known to the Working Group.

[1] http://www.w3.org/2014/Process-20140801/#first-wd

**Comment by tidoust** [comment]
Note the should requirements do not really apply to publication as First Public Working Draft so I'm marking them as done. I'll work on the
